# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    environment:
      TEST_RESULTS: /tmp/test-results

    working_directory: /go/src/github.com/carlcui/expressive
    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: install package dependency for lli
          command: |
            sudo apt-get update
            sudo apt-get install -y libncurses5

      - run:
          name: install go dependenies
          command: |
            go get -v ./...

      - run:
          name: Run unit tests
          command: |
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml

      - run:
          name: Build expressive
          command: |
            bash build.sh

      - run:
          name: e2e tests
          command: |
            bash test_e2e.sh ci

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
