# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      - image: nwtgck/pre-built-llvm-clang:4.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    environment:
      TEST_RESULTS: /tmp/test-results

    working_directory: /go/src/github.com/carlcui/expressive
    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run: go get github.com/jstemmer/go-junit-report

      # specify any bash command here prefixed with `run: `
      - run: go get -v ./...

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out

      - run:
          name: Build expressive
          command: |
            bash build.sh

      - run:
          name: e2e tests
          command: |
            expressive -d ./tests -f test1.exp --outDir ./dist
            lli-4.0.0 dist/test1.s

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
